set(_CATKIN_CURRENT_PACKAGE "realsense_simulation")
set(realsense_simulation_VERSION "0.0.2")
set(realsense_simulation_MAINTAINER "sergiomoyano <sergio.moyano@pal-robotics.com>")
set(realsense_simulation_PACKAGE_FORMAT "2")
set(realsense_simulation_BUILD_DEPENDS )
set(realsense_simulation_BUILD_EXPORT_DEPENDS )
set(realsense_simulation_BUILDTOOL_DEPENDS "catkin")
set(realsense_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(realsense_simulation_EXEC_DEPENDS "xacro")
set(realsense_simulation_RUN_DEPENDS "xacro")
set(realsense_simulation_TEST_DEPENDS "rosunit")
set(realsense_simulation_DOC_DEPENDS )
set(realsense_simulation_URL_WEBSITE "")
set(realsense_simulation_URL_BUGTRACKER "")
set(realsense_simulation_URL_REPOSITORY "")
set(realsense_simulation_DEPRECATED "")